server:
  port: 8002
spring:
  application:
    name: pay-service
  datasource:
    platform: h2
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:h2:mem:default
    driver-class-name: org.h2.Driver
    username: sa
    password: sa
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


swagger:
  enabled: true
  title: pay-service
  description: 支付模块服务
  base-package: com.github.com.github.pay.controller
  version: 1.0.0
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${spring.application.instance_id:${server.port}}
  client:
    service-url:
      defaultZone: http://${eureka.host:127.0.0.1}:${eureka.port:7001}/eureka/