server:
  port: 8001
spring:
  application:
    name: pay-service
  datasource:
    platform: h2
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:h2:mem:default
    driver-class-name: org.h2.Driver
    username: sa
    password: sa
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true