server:
  port: 7001
spring:
  application:
    name: eureka-server
eureka:
  instance:
    prefer-ip-address: true
    hostname: eureka7001.com
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${spring.application.instance_id:${server.port}}
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka/